---
abstract: 'A simple library to write AMF clients.'
author:
  - 'Alberto Attilio Reggiori, <areggiori@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AMF-Connection
no_index:
  directory:
    - t
    - inc
requires:
  LWP::UserAgent: 5.829
  Storable::AMF: 0.71
version: 0.32
