--- #YAML:1.0
name:               AMF-Connection
version:            0.21
abstract:           A simple library to write AMF clients.
author:
    - Alberto Attilio Reggiori, <areggiori@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP::UserAgent:  5.829
    Storable::AMF:   0.71
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
